---
patterns:
- note: irc
  example: m -> akerl@irc-node -p20 (guest)
  short: '^m$'
  long: '-p20 -oTCPKeepAlive=no akerl@#{expand("irc")}'
- note: irc root
  example: mr -> root@irc-node
  short: '^mr$'
  long: '-oTCPKeepAlive=no root@#{expand("irc")}'
expansions:
  irc:
  - 52.45.144.244
...

