---
patterns:
- note: IRC node
  example: m -> akerl@irc-node
  short: '^m$'
  long: '-p20 -oTCPKeepAlive=no akerl@#{shortcut("irc")}'
- note: IRC host
  example: mr -> root@irc-node
  short: '^mr$'
  long: '-oTCPKeepAlive=no root@#{shortcut("irc")}'
shortcuts:
  irc: 52.45.144.244
...

