---
patterns:
    -   note: cluster
        example: m -> akerl@miro.a-rwx.org -p20 (guest)
        short: '^([mgo])$'
        long: '-p20 -A4 -oTCPKeepAlive=no #{shortcut("unsigned")} #{expand($1)}.a-rwx.org'
    -   note: cluster dock0
        example: mr -> root@miro.a-rwx.org
        short: '^([mgo])r$'
        long: '-A4 -oTCPKeepAlive=no #{shortcut("unsigned")} root@#{expand($1)}.a-rwx.org'
expansions:
    miro:
        - m
    olhado:
        - o
    grego:
        - g
shortcuts:
    unsigned: '-oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no'
...

